name: GCS to Azure Transfer

on:
  workflow_dispatch:

jobs:
  transfer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Transfer data from GCS to Azure
        run: |
          # Set up AzCopy environment variables
          export AZCOPY_SOURCE="https://storage.cloud.google.com/shagok-velero-backup"
          export AZCOPY_DEST="https://gcpsyncazure.blob.core.windows.net?sv=2022-11-02&ss=bfqt&srt=co&sp=rwdlacupiytfx&se=2024-06-17T23:29:05Z&st=2023-08-05T15:29:05Z&spr=https&sig=%2BlrzkX7hRvzv7nEZQmzzhw2ppW1lDvBJW8H6cV3k6io%3D"
          azcopy --version
          # Replace with your AzCopy command
          azcopy copy "$AZCOPY_SOURCE" "$AZCOPY_DEST" --recursive=true
