name: GCS to Azure Transfer

on:
  schedule:
    - cron: '*/120 * * * *'  # Runs every minute

jobs:
  transfer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Transfer data from GCS to Azure
        run: |
          # Set up AzCopy environment variables
          export AZCOPY_SOURCE="https://storage.cloud.google.com/shagok-velero-backup"
          export AZCOPY_DEST="https://gcpsyncazure.blob.core.windows.net?${{secrets.SAS_TOKEN}}"
          azcopy --version
          # Replace with your AzCopy command
          azcopy copy "$AZCOPY_SOURCE" "$AZCOPY_DEST" --recursive=true
