name: Scheduled Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  scheduled_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "hello its a cron job"
