name: "Google cloud shell"

on:
  workflow_dispatch:

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'create velero service account'
      run: |
        echo "-------Download and Install verlero CLI if needed"
          if [ ! -f ~/gke-casa/velero ]; then
            wget https://github.com/vmware-tanzu/velero/releases/download/v1.10.2/velero-v1.10.2-linux-amd64.tar.gz
            tar -zxvf velero-v1.10.2-linux-amd64.tar.gz
          fi
    - name: 'Add velero to PATH'
      run: |
        mkdir -p ~/bin && cp velero-v1.10.2-linux-amd64/velero ~/bin && echo 'export PATH="$PATH:$HOME/bin"' >> ~/.bashrc && export PATH="$PATH:$HOME/bin"
        gcloud iam service-accounts keys create credentials-velero \
          --iam-account terraform-githubactions-ci-cd@eco-tenure-393916.iam.gserviceaccount.com
        gcloud container clusters get-credentials k8s-cluster --zone us-central1-a --project eco-tenure-393916
        velero install \
          --provider gcp \
          --plugins velero/velero-plugin-for-gcp:v1.1.0 \
          --bucket 'shagok-velero-backup' \
          --secret-file ./credentials-velero
        
